# Generated by Django 5.2.1 on 2025-05-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipa_casa', models.CharField(max_length=100)),
                ('equipa_fora', models.CharField(max_length=100)),
                ('golos_casa', models.IntegerField(default=0)),
                ('golos_fora', models.IntegerField(default=0)),
                ('hora', models.TimeField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jogos.jornada')),
            ],
        ),
    ]
